# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04task\"6\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x14\n\x06TaskID\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x08TaskList\x12\x19\n\x05tasks\x18\x01 \x03(\x0b\x32\n.task.Task\"\x07\n\x05\x45mpty2\xd4\x01\n\x0bTaskManager\x12&\n\nCreateTask\x12\n.task.Task\x1a\x0c.task.TaskID\x12#\n\x07GetTask\x12\x0c.task.TaskID\x1a\n.task.Task\x12%\n\nUpdateTask\x12\n.task.Task\x1a\x0b.task.Empty\x12\'\n\nDeleteTask\x12\x0c.task.TaskID\x1a\x0b.task.Empty\x12(\n\tListTasks\x12\x0b.task.Empty\x1a\x0e.task.TaskListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=20
  _globals['_TASK']._serialized_end=74
  _globals['_TASKID']._serialized_start=76
  _globals['_TASKID']._serialized_end=96
  _globals['_TASKLIST']._serialized_start=98
  _globals['_TASKLIST']._serialized_end=135
  _globals['_EMPTY']._serialized_start=137
  _globals['_EMPTY']._serialized_end=144
  _globals['_TASKMANAGER']._serialized_start=147
  _globals['_TASKMANAGER']._serialized_end=359
# @@protoc_insertion_point(module_scope)
